name: molc
description: A Flutter state management package separating UI state Models from business Logic.
version: 0.2.1
homepage: https://github.com/Icyoung/MoLc
repository: https://github.com/Icyoung/MoLc
issue_tracker: https://github.com/Icyoung/MoLc/issues
topics:
  - flutter
  - state-management
  - inherited-widget

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
