name: molc
description: A ui component base on provider.
version: 0.1.1
homepage: https://github.com/Icyoung/MoLc

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=1.12.13+hotfix.5'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
